### ISSUE TITLE
Criar um exception handler global

### ISSUE THREAD

**Issue by jlenon7** [RobsonTrasel/api-comments#1]
Cria um global exception handler usando uma middleware do Express ao invés de ficar fazendo esses `try`/`catch` dentro das controllers. Dessa forma você vai seguir um dos princípios do [**S**OLID **S**ingle Responsability Principle](https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#single-responsibility-principle).

No seu arquivo [src/server/server.ts](https://github.com/RobsonTrasel/api-comments/blob/master/src/server/server.ts) você pode adicionar uma Middleware que vai pegar os erros da aplicação globalmente.

```ts
import express from 'express'
import router from '../routes/api.routes'

const app = express()

// ---
app.use((err, req, res, next) => {
    const status = err.statusCode || 500;
    const message = err.message || 'Internal Server Error';

    const body = {
        status,
        message
    }

    if (process.env.NODE_ENV === 'development') {
      body.stack = err.stack
    }

    res.status(status).json(body)
})
// ---

app.use(express.json())
app.use('/api', router)
app.listen(3000, () => {
    console.log('[Server] iniciado com sucesso')
})
```

Agora vamos usar de exemplo o método `getComments` da sua [src/controllers/comments/comments.controller.ts](https://github.com/RobsonTrasel/api-comments/blob/master/src/controllers/comments/comments.controller.ts). Não precisamos mais do `try`/`catch` por que se qualquer error acontecer antes de chegar na linha `return res.status(200).json(result.rows)`, vai cair lá na nossa Middleware de tratamento de erros.

```ts
async getComments(req: Request, res: Response) {
      const limit = Number(req.query.limit) || 10;
      const offset = Number(req.query.offset) || 0;
      
      const result = await client.query(`SELECT * FROM comments WHERE status = 'aprovado' LIMIT ${limit} OFFSET ${offset}`);
      
      return res.status(200).json(result.rows);
}
```

Pronto, agora sua Controller tem menos responsabilidade e seu código tá menos acoplado, assim como os erros da sua aplicação, vão sempre cair no mesmo lugar. Seu método `getComments` agora tem **três** responsabilidades:

- Serialização do queries param `limit` e `offset`
- Busca no banco de dados
- Receber requests e responder

O ideal é que uma Controller chegue ao ponto de só receber e responder requests (Por isso ela se chama Controller, Controlador, ela só determina o fluxo do vai e vem). Você pode chegar nesse nível criando uma Middleware (`PaginationMiddleware`) e colocar ela só nas rotas de listagem. Ela vai ser responsável por serializar os queries `limit` e `offset` fazendo parse deles pra `number` e setando um valor default caso eles não existam. E também criando uma Service para fazer as consultas no banco de dados.

**Comment by RobsonTrasel** [comment]
Opa querido, com toda certeza, ja estava pensando nisso, com toda certeza irei fazer, agradeço o comentario, sugiro que vá acompanhando para ver o resultado final!

**Comment by jlenon7** [comment]
Bem melhor agora 👍

**Comment by RobsonTrasel** [comment]
Obrigado pela ajuda @jlenon7 !!
